apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "node-red-ml.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "node-red-ml.name" . }}
    helm.sh/chart: {{ include "node-red-ml.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: node-red-ml
    release: node-red-ml
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ include "node-red-ml.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ include "node-red-ml.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 1880
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http    
          env:
            - name: FLOWS
              value: "{{ .Values.flows }}"
            - name: NODE_OPTIONS
              value: "{{ .Values.nodeOptions }}"
            - name: TZ
              value: "{{ .Values.timezone }}"
          volumeMounts:
            - name: data
              mountPath: /data  
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: config-volume
          configMap:  
            name: node-red-ml         
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      securityContext:
        fsGroup: 1001
